Kubernetes intro
otus-kuber-2020-07/Mikhail-M_platform pull request #3
Opened 2020-08-07 20:00 UTC by Mikhail-M

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist:
 - [ ] Выставлен label с темой домашнего задания

2020-08-10 06:22 UTC, Jasstkn requested changes
Добрый день. В целом домашнее задание выполнено верно. Но вы потеряли запуск нджинкса не от рута (смотрите соответствующий комментарий). 
Пример можно посмотреть тут: https://medium.com/better-programming/running-a-container-with-a-non-root-user-e35830d1f42a, не забудьте про соответствующий UID :)

2020-08-10 06:22 UTC, Jasstkn commented on kubernetes-intro/web/Dockerfile
> +COPY nginx.conf /etc/nginx/nginx.conf
Не увидела выполнения 3его пункта со слайда 2.12 - запуск от юзера с UID 1001.

2020-08-10 20:08 UTC, Mikhail-M commented
> Добрый день. В целом домашнее задание выполнено верно. Но вы потеряли запуск нджинкса не от рута (смотрите соответствующий комментарий).
> Пример можно посмотреть тут: https://medium.com/better-programming/running-a-container-with-a-non-root-user-e35830d1f42a, не забудьте про соответствующий UID :)

Теперь у меня 403 на localhost:8000, заходил в контейнер на кубере, там /app пусто, не подскажете в чем тут дело? Если в этот образ docker run -v ${PWD}/app:/app делать, то работает

2020-08-11 08:37 UTC, Mikhail-M commented
> > Добрый день. В целом домашнее задание выполнено верно. Но вы потеряли запуск нджинкса не от рута (смотрите соответствующий комментарий).
> > Пример можно посмотреть тут: https://medium.com/better-programming/running-a-container-with-a-non-root-user-e35830d1f42a, не забудьте про соответствующий UID :)
> 
> Теперь у меня 403 на localhost:8000, заходил в контейнер на кубере, там /app пусто, не подскажете в чем тут дело? Если в этот образ docker run -v ${PWD}/app:/app делать, то работает

2020-08-11 08:37 UTC, Mikhail-M commented
Кстати, мне кажется, у вас

2020-08-11 08:48 UTC, Jasstkn commented
> Кстати, мне кажется, у вас

С докерфайлом все довольно просто: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/Dockerfile

В nginx.conf Нужно добавить немного магии: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/nginx.conf

2020-08-11 08:50 UTC, Mikhail-M commented
> > Кстати, мне кажется, у вас
> 
> С докерфайлом все довольно просто: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/Dockerfile
> 
> В nginx.conf Нужно добавить немного магии: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/nginx.conf

а в альфене не пропатченный nginx?
спасибо, попробую пошаманить

2020-08-11 09:09 UTC, Jasstkn commented
> > > Кстати, мне кажется, у вас
> 
> > 
> 
> > С докерфайлом все довольно просто: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/Dockerfile
> 
> > 
> 
> > В nginx.conf Нужно добавить немного магии: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/nginx.conf
> 
> 
> 
> а в альфине не пропатченный nginx?
> 
> спасибо, попробую пошаманить

Насколько я знаю нет. Но ещё видела варианты уже готового образа с не рутовым нджинксом то ли от битнами, то ли еще от какой-то крупной компании - можете погуглить :)

2020-08-11 09:14 UTC, Mikhail-M commented
> > Кстати, мне кажется, у вас
> 
> С докерфайлом все довольно просто: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/Dockerfile
> 
> В nginx.conf Нужно добавить немного магии: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/nginx.conf

Я скопировал себе этот образ как есть, но в итоге в итоге все равно 403 и в логах

2020/08/11 09:04:40 [error] 29#29: *2 directory index of "/app/" is forbidden, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8000"

Он должен был быть рабочим и у меня что-то пошло не так в другом месте или нужно докручивать?

2020-08-11 09:53 UTC, Mikhail-M commented
> > > Кстати, мне кажется, у вас
> > 
> > 
> > С докерфайлом все довольно просто: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/Dockerfile
> > В nginx.conf Нужно добавить немного магии: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/nginx.conf
> 
> Я скопировал себе этот образ как есть, но в итоге в итоге все равно 403 и в логах
> 
> 2020/08/11 09:04:40 [error] 29#29: *2 directory index of "/app/" is forbidden, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8000"
> 
> Он должен был быть рабочим и у меня что-то пошло не так в другом месте или нужно докручивать?

взял себе манифест из того репозитория, с ним работает, тогда покручу

2020-08-11 10:04 UTC, Mikhail-M commented
> > Кстати, мне кажется, у вас
> 
> С докерфайлом все довольно просто: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/Dockerfile
> 
> В nginx.conf Нужно добавить немного магии: https://raw.githubusercontent.com/otus-kuber-2019-12/Jasstkn_platform/master/kubernetes-intro/web/nginx.conf

А я нашел ошибку. Мой вариант кажется правильным, и как я писал выше, по каким-то причинам не инит контейнер не запускал свой скрипт. 

Так и происходило https://tinyurl.com/otus-k8s-intro (ссылка протухшая), добавил себе readinessProbe и оно не проходит, запилю вариант с полной ссылкой

2020-08-11 10:06 UTC, Mikhail-M commented
@Jasstkn почините?

2020-08-11 10:09 UTC, Jasstkn commented
> @Jasstkn почините?

Не очень поняла вас. Если ваш вариант работает, то хорошо - значит тесты будут зеленые.

2020-08-11 10:21 UTC, Mikhail-M commented
> > @Jasstkn почините?
> 
> Не очень поняла вас. Если ваш вариант работает, то хорошо - значит тесты будут зеленые.

вот эта ссылка никуда не ведет https://tinyurl.com/otus-k8s-intro, поэтому у меня было 403, я проверил это добавлением readinessProbe, /app/index.html не существовало


а тесты у меня не зеленые, потому что  упали тесты из доп части, что само по себе странно, так как код, отвечающий за frontend-pod-healthy.yaml не менялся вообще, а тесты зелеными уже раньше были, немного похоже на рандомные падения(у меня в истории коммитов уже раньше такое же было)

mandatory-tests/test_10_web_pod.py::test_response  ✓ TEST: Check web server responce
========================== 2 passed in 20.22 seconds ===========================

2020-08-11 10:30 UTC, Mikhail-M commented
> > > @Jasstkn почините?
> > 
> > 
> > Не очень поняла вас. Если ваш вариант работает, то хорошо - значит тесты будут зеленые.
> 
> вот эта ссылка никуда не ведет https://tinyurl.com/otus-k8s-intro, поэтому у меня было 403, я проверил это добавлением readinessProbe, /app/index.html не существовало
> 
> а тесты у меня не зеленые, потому что упали тесты из доп части, что само по себе странно, так как код, отвечающий за frontend-pod-healthy.yaml не менялся вообще, а тесты зелеными уже раньше были, немного похоже на рандомные падения(у меня в истории коммитов уже раньше такое же было)
> 
> mandatory-tests/test_10_web_pod.py::test_response ✓ TEST: Check web server responce
> ========================== 2 passed in 20.22 seconds ===========================

тест про фронт почему-то падает через раз, без изменения собственно содержимого манифеста, проблема у меня или в тесте?

![image](https://user-images.githubusercontent.com/5405304/89887083-614ad580-dbd6-11ea-9b77-ba5468921135.png)

2020-08-11 10:34 UTC, Mikhail-M commented
> > @Jasstkn почините?
> 
> Не очень поняла вас. Если ваш вариант работает, то хорошо - значит тесты будут зеленые.

Уточню. Тесты на задание 1 проходили всегда, но с урлом https://tinyurl.com/otus-k8s-intro у меня локально не поднимается под(с readinessProbe) и в браузере ссылочка не открывается, а с https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh и тесты проходят и локально все хорошо.

Это же норм?
![image](https://user-images.githubusercontent.com/5405304/89887684-678d8180-dbd7-11ea-9ee4-557550954b1a.png)

2020-08-11 17:15 UTC, Mikhail-M commented
> > > @Jasstkn почините?
> > 
> > 
> > Не очень поняла вас. Если ваш вариант работает, то хорошо - значит тесты будут зеленые.
> 
> Уточню. Тесты на задание 1 проходили всегда, но с урлом https://tinyurl.com/otus-k8s-intro у меня локально не поднимается под(с readinessProbe) и в браузере ссылочка не открывается, а с https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh и тесты проходят и локально все хорошо.
> 
> Это же не норм?
> ![image](https://user-images.githubusercontent.com/5405304/89887684-678d8180-dbd7-11ea-9ee4-557550954b1a.png)

tiny cтала открываться, верну её

2020-08-11 20:39 UTC, Jasstkn commented
> https://tinyurl.com/otus-k8s-intro

странно. если что - можете полный урл использовать
> https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh

2020-08-11 20:40 UTC, Jasstkn approved these changes
Принимаю домашку :)

2020-08-11 20:40 UTC, merged